### ISSUE TITLE
Edit endpoint for custom path style

### ISSUE THREAD

**Issue by yonzfloss** [kambur-andriy/s3-web-browser#3]
Hello, 

This is a great app, but i cant to change endpoint on .env file, can you tell me how can it work ?

Thanks.

**Comment by kambur-andriy** [comment]
Hello.
Please, describe the problem and I'll help you.

**Comment by yonzfloss** [comment]
I have s3 storage with custom endpoint like [bucket-name].[region].endpoint.tld, the problem is i cant to use the custom endpoint even though i added the AWS_S3_ENDPOINT variable in .env file.

**Comment by kambur-andriy** [comment]
You can try to change the configuration.
Open config/filesystems.php and add the 'endpoint' section to the [disks][s3]:
```
's3' => [
            'driver' => 's3',
            'key' => env('AWS_ACCESS_KEY_ID'),
            'secret' => env('AWS_SECRET_ACCESS_KEY'),
            'region' => env('AWS_DEFAULT_REGION'),
            'bucket' => env('AWS_BUCKET'),
            'endpoint' => env('AWS_S3_ENDPOINT'),
        ],
```
If this won't help, the only way will be to create custom driver, extended from the S3
[https://stackoverflow.com/questions/36928408/change-s3-endpoint-in-laravel/42850866](url)

**Comment by yonzfloss** [comment]
Great its work, Thanks for your help.

Case closed

![S3-Case](https://archive.floss.my.id/S3-Case.png)
