### ISSUE TITLE
Configure ACL for Uploading File/Images

### ISSUE THREAD

**Issue by yonzfloss** [kambur-andriy/s3-web-browser#4]
Hello again,

If I need changing the ACL to `public-read` when uploading files / images, which part of the config can I modif ?

**Comment by kambur-andriy** [comment]
Hello. 
If I am not mistaken, this is the S3 Bucket configuration, and you can't change this from the application. You can try to use temporary URLs for private buckets.

`$url = Storage::temporaryUrl(
    'file.jpg', now()->addMinutes(5)
);`

[Laravel Storage](https://laravel.com/docs/7.x/filesystem#file-urls)

**Comment by yonzfloss** [comment]
Owh, okay, thanks
